language: php

php:
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

install:
  - composer require jakub-onderka/php-parallel-lint
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    composer require php-coveralls/php-coveralls;
    composer require bmitch/churn-php;
    fi

script:
  - mkdir -p build/logs
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
  - if [ $(phpenv version-name) = "7.1" ]; then vendor/bin/churn run src; fi
 
after_success:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    travis_retry php vendor/bin/php-coveralls -v;
    fi
