version: 2
jobs:
  docs_deploy:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Deploy Docs
          command: |
            python3 -m venv venv
            . venv/bin/activate
            chmod +x .circleci/deploy-gh-pages.sh
            ./.circleci/deploy-gh-pages.sh
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - docs_deploy:
          filters:
            branches:
              only: master
